# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cdF <- function(uu, ff, verbose = 0L, bs = TRUE) {
    .Call('_mdrm_cdF', PACKAGE = 'mdrm', uu, ff, verbose, bs)
}

yhat <- function(yy, xx, theta) {
    .Call('_mdrm_yhat', PACKAGE = 'mdrm', yy, xx, theta)
}

LL <- function(th, X, Y) {
    .Call('_mdrm_LL', PACKAGE = 'mdrm', th, X, Y)
}

LLF <- function(th, X, Y) {
    .Call('_mdrm_LLF', PACKAGE = 'mdrm', th, X, Y)
}

gradA <- function(th, X, Y) {
    .Call('_mdrm_gradA', PACKAGE = 'mdrm', th, X, Y)
}

gradF <- function(th, X, Y) {
    .Call('_mdrm_gradF', PACKAGE = 'mdrm', th, X, Y)
}

drmHess <- function(th, X, Y, useF = TRUE) {
    .Call('_mdrm_drmHess', PACKAGE = 'mdrm', th, X, Y, useF)
}

fitdrm <- function(inY, inX, zero_index, TOL = 0., MAXIT = 100L, verb = 0L, method = "Brent", justBeta = FALSE, conv = "func") {
    .Call('_mdrm_fitdrm', PACKAGE = 'mdrm', inY, inX, zero_index, TOL, MAXIT, verb, method, justBeta, conv)
}

drmBoot <- function(y, x, nBoot, zero_index, TOL = 0, MAXIT = 100L, verb = 0L, method = "Brent") {
    .Call('_mdrm_drmBoot', PACKAGE = 'mdrm', y, x, nBoot, zero_index, TOL, MAXIT, verb, method)
}

